-- En este archivo deben estar tus ejercicios de consultas sql

--1.
SELECT E.NOMBRES + " " + E.APELLIDOS AS "NOMBRE"
FROM EMPLEADOS E
ORDER BY E.NOMBRES DESC

--2.
SELECT E.NOMBRES + " " + E.APELLIDOS AS "NOMBRE", P.PUESTO AS "PUESTO", L.LOCALIDAD AS "LOCALIDAD"
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D
ON E.DEPARTAMENTO_ID = D.ID
INNER JOIN LOCALIDADES L
ON D.LOCALIDAD_ID = L.ID
INNER JOIN PUESTOS P
ON E.PUESTO_ID = P.ID
WHERE P.PUESTO = 'Soporte'

--3.
SELECT E.NOMBRES + " " + E.APELLIDOS AS "NOMBRE"
FROM EMPLEADOS E
WHERE E.NOMBRES LIKE '%o'

--4.
SELECT E.NOMBRES + " " + E.APELLIDOS AS "NOMBRE", E.SUELDO AS "SUELDO", L.LOCALIDAD AS "LOCALIDAD"
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D
ON E.DEPARTAMENTO_ID = D.ID
INNER JOIN LOCALIDADES L
ON D.LOCALIDAD_ID = L.ID
WHERE L.LOCALIDAD = 'Carlos Paz'

--5.
SELECT E.NOMBRES + " " + E.APELLIDOS AS "NOMBRE", E.SUELDO AS "SUELDO", L.LOCALIDAD AS "LOCALIDAD"
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D
ON E.DEPARTAMENTO_ID = D.ID
INNER JOIN LOCALIDADES L
ON D.LOCALIDAD_ID = L.ID
WHERE E.SUELDO BETWEEN 10000 AND 13000

--6.
SELECT D.DENOMINACION AS "DEPARTAMENTO", COUNT(E.ID) AS "NUMERO DE EMPLEADOS"
FROM DEPARTAMENTOS D
INNER JOIN EMPLEADOS E
ON D.ID = E.DEPARTAMENTO_ID
WHERE COUNT(E.ID) > 5

--7.
SELECT E.NOMBRES + " " + E.APELLIDOS AS "NOMBRE"
FROM EMPLEADOS E
INNER JOIN PUESTOS P
ON E.PUESTO_ID = P.ID
WHERE P.PUESTO = 'Analista' OR P.PUESTO = 'Programador'

--8.
SELECT AVG(E.SUELDO) AS "SUELDO PROMEDIO"
FROM EMPLEADOS E

--9.
SELECT MAX(E.SUELDO) AS "SUELDO MAXIMO"
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D
ON E.DEPARTAMENTO_ID = D.ID
WHERE D.ID = 10

--10.
SELECT MIN(E.SUELDO) AS "SUELDO MINIMO"
FROM EMPLEADOS E
INNER JOIN DEPARTAMENTOS D
ON E.DEPARTAMENTO_ID = D.ID
WHERE D.DENOMINACION = 'Soporte'

--11.
SELECT P.PUESTO AS "PUESTO", SUM(E.SUELDO) AS "SUMA DE SUELDOS"
FROM EMPLEADOS E
INNER JOIN PUESTOS P
ON E.PUESTO_ID = P.ID
GROUP BY P.PUESTO